[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "--cfg", "openssl_vendored"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "--cfg", "openssl_vendored"]
